spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://pornhub.com
          predicates:
            - Query=url,av
        - id: qq_route
          uri: https://xvideos.com
          predicates:
            - Query=url,xv
          #精确的路由，放在高优先级
        - id: product_route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api(?<segment>/?.*), /$\{segment}

        - id: third_party_route
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>/?.*), /$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api(?<segment>/?.*), /renren-fast/$\{segment}


##前端项目发送请求，都带有api前缀，/api
##前端发送的请求，并没有转到renren-fast，http://localhost:88/api/captcha.jpg?uuid=ec60b91a-cd19-4270-8bcc-f335b1b9e4b1
## 期望路径 localhost:8080/renren-fast/captcha.jpg